name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
        name: Install Dependencies
      - run: yarn format --check
        name: prettier --check
      - run: yarn lint
        name: tslint
      - run: yarn test
        name: test
      - run: yarn test:e2e
        name: test:e2e
